package Example::Person::PhoneType;

use strict;
use warnings;

# Enum values
use constant {
    MOBILE => 0,
    HOME => 1,
    WORK => 2,
};

# Export all constants
our @EXPORT_OK = qw(
    MOBILE
    HOME
    WORK
);

# Add encode method
sub encode {
    my ($value) = @_;
    require Proto::PL::Runtime;
    return Proto::PL::Runtime::_encode_varint($value);
}

# Add decode method
sub decode {
    my ($bytes) = @_;
    require Proto::PL::Runtime;
    my ($value, $consumed) = Proto::PL::Runtime::_decode_varint($bytes, 0);
    return $value;
}

1;

__END__

=head1 NAME

Example::Person::PhoneType - Protocol Buffers enum

=head1 SYNOPSIS

    use Example::Person::PhoneType;
    
    my $value = RED;  # Imported constant

=head1 DESCRIPTION

This module defines constants for a Protocol Buffers enum.

=head1 VALUES

=head2 MOBILE = 0

=head2 HOME = 1

=head2 WORK = 2


=head1 AUTHOR

Generated by pl_protoc

=cut
